// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcQrEvD5SYge_F24EdS2yxgVHf_pusazA',
    appId: '1:511812979996:web:b747811280c38fefa2bed9',
    messagingSenderId: '511812979996',
    projectId: 'fir-test-f2b88',
    authDomain: 'fir-test-f2b88.firebaseapp.com',
    storageBucket: 'fir-test-f2b88.firebasestorage.app',
    measurementId: 'G-2E2PB8D9HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR1csUN-nvrqbJc6g2LALSNV375wPns-k',
    appId: '1:511812979996:android:893bd23fe3a341dfa2bed9',
    messagingSenderId: '511812979996',
    projectId: 'fir-test-f2b88',
    storageBucket: 'fir-test-f2b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_4ZO-d89grTI6USe3aZuwTvP4f2maPA',
    appId: '1:511812979996:ios:5df5acce97d2e619a2bed9',
    messagingSenderId: '511812979996',
    projectId: 'fir-test-f2b88',
    storageBucket: 'fir-test-f2b88.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_4ZO-d89grTI6USe3aZuwTvP4f2maPA',
    appId: '1:511812979996:ios:5df5acce97d2e619a2bed9',
    messagingSenderId: '511812979996',
    projectId: 'fir-test-f2b88',
    storageBucket: 'fir-test-f2b88.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcQrEvD5SYge_F24EdS2yxgVHf_pusazA',
    appId: '1:511812979996:web:f22ea28e5b17c958a2bed9',
    messagingSenderId: '511812979996',
    projectId: 'fir-test-f2b88',
    authDomain: 'fir-test-f2b88.firebaseapp.com',
    storageBucket: 'fir-test-f2b88.firebasestorage.app',
    measurementId: 'G-13H0DMGF3M',
  );
}
